FROM ubuntu:latest
RUN apt-get update -y && apt-get install software-properties-common -y && add-apt-repository ppa:neovim-ppa/unstable && apt-get update -y && apt-get install neovim -y && \
apt-get install ranger -y && apt-get install -y zsh   && apt-get install ripgrep && apt install -y tmux && apt install -y fd-find && mv /usr/bin/fdfind /usr/bin/fd && apt install wget -y && apt install -y git && apt install -y gcc

# RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/forgocode/dotfiles.git

