vim.keymap.set("n", "<leader>g", ":Git<CR>", vim.keymapping.opts)
vim.keymap.set("n", "<leader>gpl", ":Git pull<CR>", vim.keymapping.opts)
vim.keymap.set("n", "<leader>gps", ":Git push<CR>", vim.keymapping.opts)
vim.keymap.set("n", "<leader>gl", ":Git log<CR>", vim.keymapping.opts)
vim.keymap.set("n", "<leader>gd", ":Git diff<CR>", vim.keymapping.opts)
